-- Gessa Restore + Subscription + Referral + API Keys — Database Migration

-- ============================================================
-- 1. New Tables
-- ============================================================

-- Image versioning for restoration
CREATE TABLE IF NOT EXISTS "ArtworkImageVersion" (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "artworkId" UUID NOT NULL REFERENCES "Artwork"(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('original', 'restored', 'published')),
  url TEXT NOT NULL,
  width INT,
  height INT,
  metadata JSONB DEFAULT '{}',
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_image_version_artwork ON "ArtworkImageVersion"("artworkId");

-- Async restore job tracking
CREATE TABLE IF NOT EXISTS "RestoreJob" (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "artworkId" UUID NOT NULL REFERENCES "Artwork"(id) ON DELETE CASCADE,
  "userId" UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'queued' CHECK (status IN ('queued', 'processing', 'ready', 'failed')),
  mode TEXT DEFAULT 'faithful' CHECK (mode IN ('faithful', 'gallery')),
  error TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "startedAt" TIMESTAMP WITH TIME ZONE,
  "completedAt" TIMESTAMP WITH TIME ZONE
);

-- Subscription cache (synced from Stripe via webhook)
CREATE TABLE IF NOT EXISTS "Subscription" (
  id TEXT PRIMARY KEY,
  "userId" UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'inactive',
  tier TEXT NOT NULL DEFAULT 'free',
  "stripeSubscriptionId" TEXT,
  "stripeCustomerId" TEXT,
  "currentPeriodStart" TIMESTAMP WITH TIME ZONE,
  "currentPeriodEnd" TIMESTAMP WITH TIME ZONE,
  "cancelAtPeriodEnd" BOOLEAN DEFAULT FALSE,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_subscription_user ON "Subscription"("userId");

-- Tier pricing and limits
CREATE TABLE IF NOT EXISTS "TierLimit" (
  tier TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  "monthlyTransformations" INT NOT NULL,
  "maxRegenerations" INT NOT NULL DEFAULT 3,
  "customDomains" BOOLEAN DEFAULT FALSE,
  "apiAccess" BOOLEAN DEFAULT FALSE,
  "prioritySupport" BOOLEAN DEFAULT FALSE,
  "priceMonthlyCents" INT,
  "priceYearlyCents" INT
);

-- Seed tier data
INSERT INTO "TierLimit" (tier, name, "monthlyTransformations", "maxRegenerations", "customDomains", "apiAccess", "prioritySupport", "priceMonthlyCents", "priceYearlyCents")
VALUES
  ('free', 'Free', 3, 3, FALSE, FALSE, FALSE, 0, 0),
  ('artist', 'Artist', 30, 5, FALSE, TRUE, FALSE, 1500, 15000),
  ('studio', 'Studio', 120, 10, TRUE, TRUE, TRUE, 3500, 35000),
  ('gallery', 'Gallery', 500, 20, TRUE, TRUE, TRUE, 6900, 69000)
ON CONFLICT (tier) DO NOTHING;

-- Monthly transformation usage tracking
CREATE TABLE IF NOT EXISTS "TransformationUsage" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  "artworkId" UUID REFERENCES "Artwork"(id) ON DELETE SET NULL,
  count INT NOT NULL DEFAULT 1,
  "periodStart" TIMESTAMP WITH TIME ZONE NOT NULL,
  "periodEnd" TIMESTAMP WITH TIME ZONE NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE("userId", "artworkId", "periodStart")
);

CREATE INDEX IF NOT EXISTS idx_usage_user_period ON "TransformationUsage"("userId", "periodStart");

-- Referral tracking
CREATE TABLE IF NOT EXISTS "Referral" (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "referrerId" UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  "refereeId" UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'bonus_applied')),
  "transformationBonus" INT DEFAULT 0,
  "referredAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "bonusAppliedAt" TIMESTAMP WITH TIME ZONE,
  UNIQUE("referrerId", "refereeId")
);

-- Referral program settings
CREATE TABLE IF NOT EXISTS "ReferralProgram" (
  id TEXT PRIMARY KEY DEFAULT 'default',
  "referrerBonus" INT DEFAULT 5,
  "refereeBonus" INT DEFAULT 3,
  "maxReferralsPerUser" INT
);

INSERT INTO "ReferralProgram" (id, "referrerBonus", "refereeBonus")
VALUES ('default', 5, 3)
ON CONFLICT (id) DO NOTHING;

-- User API keys for agent access
CREATE TABLE IF NOT EXISTS "ApiKey" (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "userId" UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  key TEXT UNIQUE NOT NULL,
  "keyPrefix" TEXT NOT NULL,
  scopes TEXT[] DEFAULT '{}',
  "lastUsedAt" TIMESTAMP WITH TIME ZONE,
  "expiresAt" TIMESTAMP WITH TIME ZONE,
  "isActive" BOOLEAN DEFAULT TRUE,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_api_key_user ON "ApiKey"("userId");
CREATE INDEX IF NOT EXISTS idx_api_key_key ON "ApiKey"(key);

-- ============================================================
-- 2. Update Existing Tables
-- ============================================================

-- Add restore confirmation fields to Artwork
ALTER TABLE "Artwork"
  ADD COLUMN IF NOT EXISTS "userConfirmed" BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "disclaimerAccepted" BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "confirmedAt" TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS "disclaimerAcceptedAt" TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS "publishedSourceVersionId" UUID,
  ADD COLUMN IF NOT EXISTS "publishedSourceVersionType" TEXT,
  DROP COLUMN IF EXISTS "restoredImageUrl";

-- Instead, restoredImageUrl is tracked in ArtworkImageVersion
-- Add a view or derived field if needed

-- Add referral fields to ArtistProfile
ALTER TABLE "ArtistProfile"
  ADD COLUMN IF NOT EXISTS "referralCode" TEXT UNIQUE DEFAULT encode(gen_random_bytes(4), 'hex'),
  ADD COLUMN IF NOT EXISTS "referredBy" TEXT,
  ADD COLUMN IF NOT EXISTS "transformationCredits" INT DEFAULT 5;

-- ============================================================
-- 3. Functions
-- ============================================================

-- Check if user can perform a transformation
CREATE OR REPLACE FUNCTION check_transformation_allowed(p_user_id UUID)
RETURNS BOOLEAN AS $$
DECLARE
  v_tier TEXT;
  v_limit INT;
  v_used INT;
  v_credits INT;
  v_period_start TIMESTAMPTZ;
BEGIN
  -- Get user's subscription tier
  SELECT s.tier INTO v_tier
  FROM "Subscription" s
  WHERE s."userId" = p_user_id AND s.status = 'active'
  ORDER BY s."createdAt" DESC LIMIT 1;

  IF v_tier IS NULL THEN
    v_tier := 'free';
  END IF;

  -- Get tier limit
  SELECT "monthlyTransformations" INTO v_limit
  FROM "TierLimit" WHERE tier = v_tier;

  -- Get credits (bonus from referrals)
  SELECT COALESCE("transformationCredits", 0) INTO v_credits
  FROM "ArtistProfile" WHERE "userId" = p_user_id;

  -- Get current month usage
  v_period_start := date_trunc('month', NOW());
  SELECT COALESCE(SUM(count), 0) INTO v_used
  FROM "TransformationUsage"
  WHERE "userId" = p_user_id AND "periodStart" >= v_period_start;

  -- Allow if within limit OR has bonus credits
  RETURN v_used < v_limit OR v_credits > 0;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Record transformation usage (with credit priority)
CREATE OR REPLACE FUNCTION record_transformation(p_user_id UUID, p_artwork_id UUID)
RETURNS VOID AS $$
DECLARE
  v_period_start TIMESTAMPTZ;
  v_period_end TIMESTAMPTZ;
  v_credits INT;
BEGIN
  v_period_start := date_trunc('month', NOW());
  v_period_end := v_period_start + INTERVAL '1 month';

  -- Check if user has bonus credits to use first
  SELECT COALESCE("transformationCredits", 0) INTO v_credits
  FROM "ArtistProfile" WHERE "userId" = p_user_id;

  IF v_credits > 0 THEN
    -- Use a credit instead of monthly limit
    UPDATE "ArtistProfile"
    SET "transformationCredits" = "transformationCredits" - 1
    WHERE "userId" = p_user_id;
  ELSE
    -- Record against monthly limit
    INSERT INTO "TransformationUsage" ("userId", "artworkId", count, "periodStart", "periodEnd")
    VALUES (p_user_id, p_artwork_id, 1, v_period_start, v_period_end)
    ON CONFLICT ("userId", "artworkId", "periodStart")
    DO UPDATE SET count = "TransformationUsage".count + 1;
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Award referral bonus when referee subscribes
CREATE OR REPLACE FUNCTION award_referral_bonus(p_referee_id UUID)
RETURNS VOID AS $$
DECLARE
  v_referrer_code TEXT;
  v_referrer_id UUID;
  v_referrer_bonus INT;
  v_referee_bonus INT;
BEGIN
  -- Get who referred this user
  SELECT "referredBy" INTO v_referrer_code
  FROM "ArtistProfile" WHERE "userId" = p_referee_id;

  IF v_referrer_code IS NULL THEN
    RETURN;
  END IF;

  -- Find the referrer
  SELECT "userId" INTO v_referrer_id
  FROM "ArtistProfile" WHERE "referralCode" = v_referrer_code;

  IF v_referrer_id IS NULL THEN
    RETURN;
  END IF;

  -- Get bonus amounts
  SELECT "referrerBonus", "refereeBonus" INTO v_referrer_bonus, v_referee_bonus
  FROM "ReferralProgram" WHERE id = 'default';

  -- Award bonuses
  UPDATE "ArtistProfile"
  SET "transformationCredits" = "transformationCredits" + COALESCE(v_referrer_bonus, 5)
  WHERE "userId" = v_referrer_id;

  UPDATE "ArtistProfile"
  SET "transformationCredits" = "transformationCredits" + COALESCE(v_referee_bonus, 3)
  WHERE "userId" = p_referee_id;

  -- Mark referral as completed
  UPDATE "Referral"
  SET status = 'bonus_applied',
      "transformationBonus" = COALESCE(v_referrer_bonus, 5),
      "bonusAppliedAt" = NOW()
  WHERE "refereeId" = p_referee_id AND status = 'completed';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- 4. RLS Policies for new tables
-- ============================================================

ALTER TABLE "ArtworkImageVersion" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own image versions" ON "ArtworkImageVersion" FOR SELECT TO authenticated USING (
  "artworkId" IN (SELECT id FROM "Artwork" WHERE "artistProfileId" IN (SELECT id FROM "ArtistProfile" WHERE "userId" = auth.uid()))
);
CREATE POLICY "Public read published image versions" ON "ArtworkImageVersion" FOR SELECT TO anon USING (
  "artworkId" IN (SELECT id FROM "Artwork" WHERE status = 'published')
);

ALTER TABLE "RestoreJob" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own restore jobs" ON "RestoreJob" FOR SELECT TO authenticated USING ("userId" = auth.uid());

ALTER TABLE "Subscription" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own subscription" ON "Subscription" FOR SELECT TO authenticated USING ("userId" = auth.uid());

ALTER TABLE "TierLimit" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Everyone can read tier limits" ON "TierLimit" FOR SELECT TO anon, authenticated USING (TRUE);

ALTER TABLE "TransformationUsage" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own usage" ON "TransformationUsage" FOR SELECT TO authenticated USING ("userId" = auth.uid());

ALTER TABLE "Referral" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own referrals" ON "Referral" FOR SELECT TO authenticated USING ("referrerId" = auth.uid() OR "refereeId" = auth.uid());

ALTER TABLE "ApiKey" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage own API keys" ON "ApiKey" FOR ALL TO authenticated USING ("userId" = auth.uid());

SELECT 'Migration complete' AS result;
